const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const { normalizePetName, petNameFor, lessonsForShift, applyAttendanceOverrides, attendanceOnDay, entryOnDay } = await import('../src/lib/classroomUpdates.js');
  assert.equal(normalizePetName('  Lua\n Nova  '), 'Lua Nova');
  assert.equal(Array.from(normalizePetName('🐉'.repeat(30))).length,24);
  const avatar = {pet:'🐉',petNames:{'🐉':'Lua','🐰':'Pipoca'}};
  assert.equal(petNameFor(avatar),'Lua');
  assert.equal(petNameFor({...avatar,pet:'🐰'}),'Pipoca');
  assert.equal(petNameFor({pet:'🐱'}),'');
  const lessons = [{title:'antiga'}, {title:'manhã',shift:'matutino'}, {title:'tarde',shift:'vespertino'}];
  assert.deepEqual(lessonsForShift(lessons,'matutino').map(l=>l.title),['manhã']);
  assert.deepEqual(lessonsForShift(lessons,'unassigned').map(l=>l.title),['antiga']);
  assert.equal(lessonsForShift(lessons,'all').length,3);
  const day='2026-09-03', keyOf=ts=>new Date(ts).toISOString().slice(0,10);
  const student={attendanceFirst:{[day]:Date.parse(day)},attendance:{[day]:'present'},attendanceOverrides:{[day]:{status:'absent'}}};
  assert.equal(entryOnDay(student,day,keyOf),true);
  assert.equal(attendanceOnDay(student,day,keyOf),'absent');
  assert.equal(applyAttendanceOverrides(student.attendance,student.attendanceOverrides)[day],'absent');
  assert.equal(student.attendance[day],'present');
  assert.equal(attendanceOnDay({},day,keyOf),'absent');
  const manualOnly={attendance:{[day]:'present'},attendanceOverrides:{[day]:{status:'present'}}};
  assert.equal(entryOnDay(manualOnly,day,keyOf),false,'Presença manual não inventa acesso');
  assert.equal(attendanceOnDay(manualOnly,day,keyOf),'present');
  const {PLATFORM_VERSION, RELEASES} = await import('../src/releases.js');
  const pkg=JSON.parse(fs.readFileSync('package.json'));
  const lock=JSON.parse(fs.readFileSync('package-lock.json'));
  assert.equal(PLATFORM_VERSION,pkg.version);
  assert.equal(lock.version,pkg.version);
  assert.equal(lock.packages[''].version,pkg.version);
  assert.equal(new Set(RELEASES.map(r=>r.version)).size,RELEASES.length);
  console.log('Nomes de pets, isolamento por turno, presença manual e versão: aprovados.');
})().catch(e=>{console.error(e);process.exitCode=1;});
