const assert = require('node:assert/strict')
const fs = require('node:fs')

const hub = fs.readFileSync('src/components/StudentMusicHub.jsx','utf8')
const app = fs.readFileSync('src/App.jsx','utf8')
const api = fs.readFileSync('api/music-search.js','utf8')
const kv = fs.readFileSync('api/kv.js','utf8')
const teacher = fs.readFileSync('src/components/ClassMusicSettings.jsx','utf8')

assert.match(hub,/Playlist da sala/)
assert.match(hub,/Minha playlist/)
assert.match(hub,/Tocando agora/)
assert.match(hub,/searchMusic/)
assert.match(app,/personalMusicTracks/)
assert.match(app,/addClassMusicTrack/)
assert.match(api,/canStudentUseMusic/)
assert.match(kv,/add_class_music_track/)
assert.match(kv,/student_not_found/)
assert.match(kv,/playlist_full/)
assert.match(kv,/safeStudentName\(studentName\)/)
assert.match(teacher,/Tocando agora/)
assert.match(teacher,/Minha playlist/)

console.log('Central de músicas oferece busca, reprodução imediata e playlists pessoal/coletiva.')
