// ── loja de acessórios do Nyx (desbloqueados com pontos de acerto) ──
export const NYX_ITEMS = [
  // skins preservam exatamente o corpo Prisma Orbital; mudam apenas cores, materiais e luzes
  { id:"skinPrismaOrbital", label:"Nyx Prisma Orbital", emoji:"🔮", slot:"skin", cost:30 },
  { id:"skinOrbita",       label:"Nyx Órbita",       emoji:"🪐", slot:"skin", cost:28 },
  { id:"skinGuardiao",     label:"Nyx Guardião",     emoji:"🛡️", slot:"skin", cost:32 },
  { id:"skinAurora",       label:"Nyx Aurora",       emoji:"🌌", slot:"skin", cost:35 },
  { id:"skinLuaNova",      label:"Nyx Lua Nova",     emoji:"🌑", slot:"skin", cost:30 },
  { id:"skinMare",         label:"Nyx Maré",         emoji:"🌊", slot:"skin", cost:34 },
  { id:"skinConstelacao",  label:"Nyx Constelação",  emoji:"✨", slot:"skin", cost:45 },
  { id:"fone",   label:"Fone de ouvido", emoji:"🎧", slot:"head", cost:5 },
  { id:"laco",   label:"Laço",           emoji:"🎀", slot:"neck", cost:8 },
  { id:"oculos", label:"Óculos escuros", emoji:"🕶️", slot:"face", cost:10 },
  { id:"chapeu", label:"Cartola",        emoji:"🎩", slot:"head", cost:15 },
  { id:"escudo", label:"Escudo",         emoji:"🛡️", slot:"shield", cost:20 },
  { id:"espada", label:"Espada",         emoji:"⚔️", slot:"hand", cost:30 },
  { id:"coroa",  label:"Coroa",          emoji:"👑", slot:"head", cost:40 },
  { id:"arco",   label:"Arco e flecha",  emoji:"🏹", slot:"hand", cost:50 },
  { id:"chapeuPirata", label:"Chapéu Pirata", emoji:"🏴‍☠️", slot:"head", cost:22 },
  // cabeça
  { id:"touca",        label:"Touca de Lã",        emoji:"🧶", slot:"head", cost:6 },
  { id:"bone",         label:"Boné",               emoji:"🧢", slot:"head", cost:8 },
  { id:"chapeuFesta",  label:"Chapéu de Festa",    emoji:"🥳", slot:"head", cost:10 },
  { id:"bandana",      label:"Bandana Ninja",      emoji:"🥷", slot:"head", cost:12 },
  { id:"gorroNatal",   label:"Gorro de Papai Noel",emoji:"🎅", slot:"head", cost:12 },
  { id:"orelhinhas",   label:"Orelhinhas de Gato", emoji:"🐱", slot:"head", cost:10 },
  { id:"tiara",        label:"Tiara",              emoji:"💎", slot:"head", cost:16 },
  { id:"capaceteObra", label:"Capacete de Obra",   emoji:"⛑️", slot:"head", cost:14 },
  { id:"foneDJ",       label:"Fone de DJ",         emoji:"🪩", slot:"head", cost:18 },
  { id:"chapeuMago",   label:"Chapéu de Mago",     emoji:"🧙", slot:"head", cost:22 },
  { id:"capelo",       label:"Capelo de Formatura",emoji:"🎓", slot:"head", cost:45 },
  // rosto
  { id:"oculosNerd",    label:"Óculos de Nerd",     emoji:"🤓", slot:"face", cost:8 },
  { id:"vendaPirata",   label:"Venda de Pirata",    emoji:"🩹", slot:"face", cost:10 },
  { id:"oculosAviador", label:"Óculos de Aviador",  emoji:"😎", slot:"face", cost:12 },
  { id:"oculos3d",      label:"Óculos 3D",          emoji:"🥽", slot:"face", cost:10 },
  { id:"monoculo",      label:"Monóculo",           emoji:"🧐", slot:"face", cost:14 },
  { id:"mascaraHeroi",  label:"Máscara de Herói",   emoji:"🎭", slot:"face", cost:18 },
  // pescoço
  { id:"cachecol",       label:"Cachecol",           emoji:"🧣", slot:"neck", cost:10 },
  { id:"golaSocial",     label:"Gola Social",        emoji:"👕", slot:"neck", cost:10 },
  { id:"colarHavaiano",  label:"Colar Havaiano",     emoji:"🌺", slot:"neck", cost:12 },
  { id:"gravataBorboleta", label:"Gravata-Borboleta",emoji:"👔", slot:"neck", cost:12 },
  { id:"colarDev",       label:"Colar </>",          emoji:"🏷️", slot:"neck", cost:14 },
  { id:"medalha",        label:"Medalha",            emoji:"🏅", slot:"neck", cost:25 },
  // mão
  { id:"sorvete",       label:"Sorvete",            emoji:"🍦", slot:"hand", cost:8 },
  { id:"guardaChuva",   label:"Guarda-chuva",       emoji:"☂️", slot:"hand", cost:10 },
  { id:"chaveInglesa",  label:"Chave Inglesa",      emoji:"🔧", slot:"hand", cost:14 },
  { id:"bandeiraCorrida", label:"Bandeira de Corrida", emoji:"🏁", slot:"hand", cost:15 },
  { id:"microfone",     label:"Microfone",          emoji:"🎤", slot:"hand", cost:16 },
  { id:"martelo",       label:"Martelo de Dev",     emoji:"🔨", slot:"hand", cost:18 },
  { id:"grimorio",      label:"Grimório Mágico",    emoji:"📖", slot:"hand", cost:18 },
  { id:"varinha",       label:"Varinha Mágica",     emoji:"🪄", slot:"hand", cost:20 },
  { id:"tecladoMini",   label:"Teclado Mecânico",   emoji:"⌨️", slot:"hand", cost:20 },
  { id:"controle",      label:"Controle de Videogame", emoji:"🎮", slot:"hand", cost:22 },
  { id:"trofeu",        label:"Taça de Troféu",     emoji:"🏆", slot:"hand", cost:30 },
  // escudo
  { id:"tampaPanela", label:"Tampa de Panela", emoji:"🥘", slot:"shield", cost:12 },
  { id:"placaStop",   label:"Placa de Stop",   emoji:"🛑", slot:"shield", cost:16 },
  { id:"livroGrosso", label:"Livro Grosso",    emoji:"📚", slot:"shield", cost:20 },
  // itens novos — materiais mais ricos (ouro, rubi, bronze, couro), incluindo o primeiro item de
  // "costas" da loja (a capa não se encaixava em nenhum encaixe existente)
  { id:"coroaPrismatica",     label:"Coroa Prismática",     emoji:"👑", slot:"head", cost:42 },
  { id:"haloOrbital",         label:"Halo Orbital",         emoji:"😇", slot:"head", cost:35 },
  { id:"viseiraHolografica",  label:"Viseira Holográfica",  emoji:"🔶", slot:"face", cost:25 },
  { id:"brincosCristal",      label:"Brincos de Cristal",   emoji:"💎", slot:"face", cost:20 },
  { id:"golaNucleo",          label:"Gola de Núcleo",       emoji:"🟤", slot:"neck", cost:22 },
  { id:"capaHeroi",           label:"Capa de Herói",        emoji:"🦸", slot:"costas", cost:55 },
];
export const DEFAULT_NYX_GEAR = { skin:null, head:null, head2:null, face:null, face2:null, neck:null, neck2:null, hand:null, hand2:null, shield:null, shield2:null, costas:null, costas2:null };
