import { Avatar } from "./Avatar.jsx";

const Shell=({title,onClose,children})=><div style={{position:"fixed",inset:0,zIndex:1100,background:"#0b0614d9",display:"flex",alignItems:"center",justifyContent:"center",padding:16}} onClick={onClose}><div className="pop" onClick={e=>e.stopPropagation()} style={{width:"min(560px,100%)",maxHeight:"86vh",overflowY:"auto",background:"linear-gradient(180deg,#231636,#1a1029)",border:"1px solid #3e2d5e",borderRadius:20,padding:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><h2 style={{margin:0,color:"#f0e9fb",fontSize:19}}>{title}</h2><button onClick={onClose} style={{background:"none",border:0,color:"#a99ac9",fontSize:22,cursor:"pointer"}}>✕</button></div>{children}</div></div>;
const row={background:"#171026",border:"1px solid #3b2a58",borderRadius:11,padding:"10px 12px",color:"#d6c9ec",fontSize:12.5,marginBottom:8};

export function StudentNotificationsModal({items,onClose}){return <Shell title="🔔 Central de novidades" onClose={onClose}>{items.length?items.map((n,i)=><div key={i} style={row}><b style={{color:n.color||"#c084fc"}}>{n.icon} {n.title}</b><div style={{marginTop:3,lineHeight:1.5}}>{n.text}</div>{n.action&&<button onClick={n.action} style={{marginTop:7,border:0,borderRadius:8,background:"#c084fc",color:"white",padding:"6px 10px",cursor:"pointer"}}>Abrir</button>}</div>):<p style={{color:"#a99ac9"}}>Tudo certo por aqui. Nenhuma novidade pendente.</p>}</Shell>}

export function StudentProfileModal({name,avatar,shift,streak,achievements,totalAchievements,nyxPoints,duelWins,typingBest,onClose}){return <Shell title="🌌 Meu perfil de jornada" onClose={onClose}><div style={{display:"flex",alignItems:"center",gap:14,marginBottom:14}}><Avatar cfg={avatar} size={76} animated/><div><h3 style={{color:"#f0e9fb",margin:0}}>{name}</h3><p style={{color:"#a99ac9",margin:"4px 0 0",fontSize:12.5}}>{shift}</p></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{[["🔥 Sequência",`${streak||0} dia(s)`],["🎖️ Conquistas",`${achievements}/${totalAchievements}`],["💰 Pontos Nyx",nyxPoints||0],["⚔️ Vitórias",duelWins||0],["🏁 Melhor digitação",typingBest?`${(typingBest.ms/1000).toFixed(1)}s`:"Ainda não jogou"]].map(([a,b])=><div key={a} style={row}><b style={{color:"#c084fc"}}>{a}</b><div style={{marginTop:4}}>{b}</div></div>)}</div></Shell>}

export function DailyMissionsModal({missions,onClose}){const done=missions.filter(m=>m.done).length;return <Shell title="☀️ Missões de hoje" onClose={onClose}><p style={{color:"#a99ac9",fontSize:12.5}}>Objetivos leves para orientar a exploração — não valem nota e não punem ninguém.</p>{missions.map(m=><div key={m.label} style={{...row,borderColor:m.done?"#34d399":"#3b2a58"}}><b style={{color:m.done?"#34d399":"#f0e9fb"}}>{m.done?"✅":"○"} {m.label}</b><div style={{color:"#776798",marginTop:3}}>{m.help}</div></div>)}<p style={{color:"#fbbf24",fontWeight:800,textAlign:"center"}}>{done}/{missions.length} concluídas hoje</p></Shell>}
